name: Check PR description

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          gh auth setup-git
          gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR description
        id: check_pr_description
        run: |
          echo "Checking PR ${{ github.event.pull_request.number }}"
          pr_description=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
          if [ -z "$pr_description" ]; then
            echo "Error: Pull request description is empty."
            exit 1
          else
            echo "Pull request description is not empty."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}