name: Check PR description

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR description
        id: check_pr_description
        run: |
          echo "Checking PR $PR_NUMBER"
          pr_description=$(gh pr view $PR_NUMBER --json body -q .body)
          if [ -z "$pr_description" ]; then
            echo "Error: Pull request description is empty."
            exit 1
          else:
            echo "Pull request description is not empty."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}